In [1]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [2]:
3 * 5  # Not shown
16 / 4 # Shown

4.0

In [3]:
print( 3 * 5 ) # Shown
print( 16 / 4 ) # Shown

15
4.0


In [4]:
# print( 3 * 5 )  <-- This code does not get run

In [5]:
# Print concatenation
print( 'Testing', 1, 2, 3 )

Testing 1 2 3


In [6]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [7]:
# Total volume of water you can carry
import math 
total_volume = math.pi*math.pow(5, 2)*17
total_volume

1335.1768777756622

In [8]:
# Do you have space for at least 2000 cm^3
if total_volume >= 2000:
    print (True)
else:
    print (False)

False


In [9]:
bottles = total_volume / 5000
bottles 

0.26703537555513246

In [10]:
# Print message to Q
"Yes, I have enough space. I can carry total_volume cm^3 of water"
print ("No, I don't have enough space. I can carry " + str(total_volume) + " cm^3 of water")

No, I don't have enough space. I can carry 1335.1768777756622 cm^3 of water


In [11]:
# Set variables
bottles = 3 
bottle_height = 16 
bottle_radius = 4 

In [12]:
# Volume of one bottle (in cm^3)
bottle_volume = math.pi*bottle_radius**2*bottle_height
# Print volume of a single bottle
print (bottle_volume)

804.247719318987


In [13]:
# Total volume
total_volume = bottle_volume * bottles
# Print total volume
print (total_volume)

2412.743157956961


In [14]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [15]:
# Read lists of locations (simply run this code block)
with open('brent.txt', 'r') as f:
    brent = f.read().splitlines()
    
with open('camden.txt', 'r') as f:
    camden = f.read().splitlines()

with open('redbridge.txt', 'r') as f:
    redbridge = f.read().splitlines()

with open('southwark.txt', 'r') as f:
    southwark = f.read().splitlines()

In [16]:
print( type(brent) )

<class 'list'>


In [17]:
# Print the first 5 locations in Camden
camden[0:5]

['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury']

In [18]:
# Print length of each list
c_length = len(camden)
b_length = len(brent)
r_length = len(redbridge)
s_length = len(southwark)

c_length == max(c_length, b_length, r_length, s_length)
print ("Camden has the most locations.")

Camden has the most locations.


In [19]:
# Is 'Newbury Park' in Redbridge?
if "Newbury Park" in redbridge: 
    print(True) 
else: 
    print(False)

# Is 'Peckham' in Brent?
if "Peckham" in brent: 
    print(True) 
else: 
    print(False) 

True
False


In [20]:
# Print minimum value in southwark
sorted(southwark)[0]
# Print maximum value in southwark
sorted(southwark)[-1]

#The lists are ordered alphabetically.

'Walworth'

In [21]:
# Brent has duplicates?
b_len = len(brent)
print (b_len > len(set(brent)))
    
# Camden has duplicates?
c_len = len(camden)
print(c_len > len(set(camden)))
# Redbridge has duplicates?
r_len = len(redbridge)
print(r_len > len(set(redbridge)))
# Southwark has duplicates?
s_len = len(southwark)
print(s_len > len(set(southwark)))

False
True
True
True


In [22]:
camden = list(set(camden))
redbridge = list(set(redbridge))
southwark = list(set(southwark))

In [23]:
# Create location_dict

location_dict = {"Brent": brent, "Camden": camden, "Redbridge": redbridge, "Southwark": southwark}

In [24]:
# Run this cell
for borough in ['Brent', 'Camden', 'Redbridge', 'Southwark']:
    print( borough in location_dict )

True
True
True
True


In [25]:
# Run this cell
brent, camden, redbridge, southwark = None, None, None, None

In [26]:
print( type(None) )

<class 'NoneType'>


In [27]:
# Create a new key-value pair for 'Inner London'
location_dict["Inner London"] = location_dict["Camden"] + location_dict["Southwark"] 
        
# Create a new key-value pair for 'Outer London'
location_dict["Outer London"] = location_dict["Brent"] + location_dict["Redbridge"]

In [28]:
print( len(location_dict['Inner London']) )
print( len(location_dict['Outer London']) )

32
35


In [29]:
import pickle

# Save object to disk
with open('location_dict.pkl', 'wb') as f:
    pickle.dump(location_dict, f)

In [30]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [31]:
import pickle

# Read object from disk
with open('location_dict.pkl', 'rb') as f:
    location_dict = pickle.load(f)

In [32]:
# Print the keys in location_dict
for keys in location_dict.keys():
    print (keys)

Brent
Camden
Redbridge
Southwark
Inner London
Outer London


In [33]:
# Write code here
if len(location_dict["Inner London"]) > len(location_dict["Outer London"]):
    print("I want to start in Inner London")
elif len(location_dict["Outer London"]) > len(location_dict["Inner London"]):
    print("I want to start in Outer London")
else: 
    print ("Either is fine. Flip a coin, Q.")

I want to start in Outer London


In [34]:
# For each key in location_dict, print the number of locations in its list
for key, value in location_dict.items(): 
    print ("{} has {} locations".format(key, len(value)))

Brent has 19 locations
Camden has 19 locations
Redbridge has 16 locations
Southwark has 13 locations
Inner London has 32 locations
Outer London has 35 locations


In [35]:
pleasant_sounding = ['Farm', 'Park', 'Hill', 'Green']
royal_sounding = ['Royal', 'Queen', 'King']

# Print first impression of each location in Outer London based on its names
for locations in location_dict["Outer London"]:
    if any(word in locations for word in pleasant_sounding):
        print(locations +  " sounds pleasant.")
    elif any(word in locations for word in royal_sounding):
        print (locations + " sounds grand.")

Brent Park sounds pleasant.
Dollis Hill sounds pleasant.
Kensal Green sounds pleasant.
Kingsbury sounds grand.
Queen's Park sounds pleasant.
Wembley Park sounds pleasant.
Park Royal sounds pleasant.
Gants Hill sounds pleasant.
Woodford Green sounds pleasant.
Seven Kings sounds grand.
Newbury Park sounds pleasant.


In [36]:
# Create pleasant_locations list using a list comprehension
pleasant_locations = [locations for locations in location_dict["Outer London"] if any(word in locations for word in pleasant_sounding)]
# Print the pleasant-sounding locations
print (pleasant_locations) 


['Brent Park', 'Dollis Hill', 'Kensal Green', "Queen's Park", 'Wembley Park', 'Park Royal', 'Gants Hill', 'Woodford Green', 'Newbury Park']


In [37]:
# Print number of pleasant-sounding locations
print (str(len(pleasant_locations)))

9


In [38]:
# Code here
def filter_locations(location_list, word_list):
    names = [locations for locations in location_list if any(word in locations for word in word_list)]
    return names

In [39]:
# Create pleasant_locations using filter_locations()
pleasant_locations = filter_locations(location_dict["Outer London"], pleasant_sounding)

# Print list of pleasant-sounding locations
print (pleasant_locations)

['Brent Park', 'Dollis Hill', 'Kensal Green', "Queen's Park", 'Wembley Park', 'Park Royal', 'Gants Hill', 'Woodford Green', 'Newbury Park']


In [40]:
# Create grand_locations using filter_locations()
grand_locations = filter_locations(location_dict["Outer London"], royal_sounding)

# Print list of grand-sounding locations
print (grand_locations)

['Kingsbury', "Queen's Park", 'Park Royal', 'Seven Kings']


In [41]:
# Display locations that sound pleasant and grand
print (set(pleasant_locations).intersection(set(grand_locations)))

{"Queen's Park", 'Park Royal'}


In [42]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [43]:
import numpy as np

In [44]:
# Create array of business_ids with values ranging from 1 to 1700
business_ids = np.arange(1, 1701)

In [45]:
# Print shape of business_ids
print(business_ids.shape)

(1700,)


In [46]:
# Print last 10 business ID's
print(business_ids[-11:])

[1690 1691 1692 1693 1694 1695 1696 1697 1698 1699 1700]


In [47]:
# Create id_matrix by reshaping business_ids to have 10 columns
id_matrix = np.reshape(business_ids, (170, 10))

# Print shape
print (id_matrix)

[[   1    2    3 ...    8    9   10]
 [  11   12   13 ...   18   19   20]
 [  21   22   23 ...   28   29   30]
 ...
 [1671 1672 1673 ... 1678 1679 1680]
 [1681 1682 1683 ... 1688 1689 1690]
 [1691 1692 1693 ... 1698 1699 1700]]


In [48]:
# Print first column of id_matrix
print(id_matrix[:,0])

[   1   11   21   31   41   51   61   71   81   91  101  111  121  131
  141  151  161  171  181  191  201  211  221  231  241  251  261  271
  281  291  301  311  321  331  341  351  361  371  381  391  401  411
  421  431  441  451  461  471  481  491  501  511  521  531  541  551
  561  571  581  591  601  611  621  631  641  651  661  671  681  691
  701  711  721  731  741  751  761  771  781  791  801  811  821  831
  841  851  861  871  881  891  901  911  921  931  941  951  961  971
  981  991 1001 1011 1021 1031 1041 1051 1061 1071 1081 1091 1101 1111
 1121 1131 1141 1151 1161 1171 1181 1191 1201 1211 1221 1231 1241 1251
 1261 1271 1281 1291 1301 1311 1321 1331 1341 1351 1361 1371 1381 1391
 1401 1411 1421 1431 1441 1451 1461 1471 1481 1491 1501 1511 1521 1531
 1541 1551 1561 1571 1581 1591 1601 1611 1621 1631 1641 1651 1661 1671
 1681 1691]


In [49]:
# Reshape business_ids to have 10 rows, with 170 businesses each

id_matrix = id_matrix.reshape(10, 170)

In [50]:
# Print the first row of id_matrix
print(id_matrix[0,:])


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]


In [51]:
# Overwrite id_matrix with flipped version
id_matrix = np.transpose(id_matrix)

# Print first column
print(id_matrix[:,0])


# Print shape of new id_matrix
print (id_matrix.shape)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]
(170, 10)


In [52]:
# Create group_min
group_min = np.min(id_matrix, axis=0)
# Print group_min
print (group_min)

[   1  171  341  511  681  851 1021 1191 1361 1531]


In [53]:
# Create group_max
group_max = np.max(id_matrix, axis=0)
# Print group_max
print (group_max)

[ 170  340  510  680  850 1020 1190 1360 1530 1700]


In [54]:
# Print range of each group
print (group_max - group_min + 1)

[170 170 170 170 170 170 170 170 170 170]


In [55]:
# Set random seed
np.random.seed(9001)
# Print selected businesses from each group
for group in range(id_matrix.shape[1]): 
    print("Group {}: {}".format(group+1, np.random.choice(id_matrix[:,group], 5, replace=False)))
    

Group 1: [  7  37 124  41  17]
Group 2: [302 261 257 323 234]
Group 3: [464 486 463 440 474]
Group 4: [645 582 666 631 553]
Group 5: [699 738 705 760 792]
Group 6: [ 995 1000  909  869  899]
Group 7: [1042 1058 1172 1122 1153]
Group 8: [1304 1275 1343 1344 1236]
Group 9: [1401 1417 1383 1387 1474]
Group 10: [1642 1687 1545 1644 1549]


In [56]:
from __future__ import print_function  # Compatability with Python 3
print('Print function ready to serve.')

Print function ready to serve.


In [57]:
import pandas as pd

In [58]:
# Read the iris dataset from a CSV file
df = pd.read_csv('C:/Users/Rx_Precious/Desktop/python/ML/Week 1 & 2/Assignments/iris.csv')

In [59]:
# Create toy_df
df_h = df.head()
df_t = df.tail()
toy_df = pd.concat([df_h, df_t])


In [60]:
# Display toy_df

toy_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [61]:
# Describe toy_df

toy_df.describe()

sepal_length  sepal_width  petal_length  petal_width
count     10.000000    10.000000     10.000000    10.000000
mean       5.590000     3.130000      3.290000     1.130000
std        0.807534     0.316403      1.995244     0.992248
min        4.600000     2.500000      1.300000     0.200000
25%        4.925000     3.000000      1.400000     0.200000
50%        5.500000     3.050000      3.250000     1.000000
75%        6.275000     3.350000      5.175000     1.975000
max        6.700000     3.600000      5.400000     2.300000

In [62]:
# Display petal_width and petal_length
petal_width = toy_df["petal_width"]
petal_length = toy_df["petal_length"]
toy_df[["petal_width", "petal_length"]]

petal_width  petal_length
0            0.2           1.4
1            0.2           1.4
2            0.2           1.3
3            0.2           1.5
4            0.2           1.4
145          2.3           5.2
146          1.9           5.0
147          2.0           5.2
148          2.3           5.4
149          1.8           5.1

In [63]:
# Create a new petal_area column
toy_df["petal_area"] = toy_df["petal_width"] * toy_df["petal_length"]

# Display toy_df
toy_df


sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     petal_area  
0          0.28  
1          0.28  
2          0.26  
3          0.30  
4          0.28  
145       11.96  
146        9.50  
147       10.40  
148       12.42  
149        9.18

In [64]:
# Display toy_df

toy_df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     petal_area  
0          0.28  
1          0.28  
2          0.26  
3          0.30  
4          0.28  
145       11.96  
146        9.50  
147       10.40  
148       12.42  
149        9.18

In [65]:
# Mask for petal_area > 10

petal_area_mask = toy_df["petal_area"] > 10 
# Display petal_area_mask
petal_area_mask

0      False
1      False
2      False
3      False
4      False
145     True
146    False
147     True
148     True
149    False
Name: petal_area, dtype: bool

In [66]:
# Mask for sepal_width > 3
sepal_width_mask = toy_df["sepal_width"] > 3

# Display sepal_width_mask
sepal_width_mask

0       True
1      False
2       True
3       True
4       True
145    False
146    False
147    False
148     True
149    False
Name: sepal_width, dtype: bool

In [67]:
# Display both masks, combined
sepal_width_mask & petal_area_mask

0      False
1      False
2      False
3      False
4      False
145    False
146    False
147    False
148     True
149    False
dtype: bool

In [68]:
# Index with both masks

toy_df[sepal_width_mask & petal_area_mask]

sepal_length  sepal_width  petal_length  petal_width    species  \
148           6.2          3.4           5.4          2.3  virginica   

     petal_area  
148       12.42

In [69]:
# Display all 'virginica' species, sorted by petal_area
toy_df[toy_df["species"] == "virginica"].sort_values("petal_area", axis=0, ascending="True")

sepal_length  sepal_width  petal_length  petal_width    species  \
149           5.9          3.0           5.1          1.8  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
145           6.7          3.0           5.2          2.3  virginica   
148           6.2          3.4           5.4          2.3  virginica   

     petal_area  
149        9.18  
146        9.50  
147       10.40  
145       11.96  
148       12.42

In [70]:
# Display all 'setosa' species
toy_df[toy_df["species"] == "setosa"].sort_values("petal_area", axis=0, ascending="True")

sepal_length  sepal_width  petal_length  petal_width species  petal_area
2           4.7          3.2           1.3          0.2  setosa        0.26
0           5.1          3.5           1.4          0.2  setosa        0.28
1           4.9          3.0           1.4          0.2  setosa        0.28
4           5.0          3.6           1.4          0.2  setosa        0.28
3           4.6          3.1           1.5          0.2  setosa        0.30

In [71]:
# Median petal_area in toy_df
toy_df.groupby("species")["petal_area"].median()

species
setosa        0.28
virginica    10.40
Name: petal_area, dtype: float64